apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-collection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collection
  template:
    metadata:
      labels:
        app: collection
    spec:
      containers:
      - name: web
        image: my-collection:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: APP_NAME
          value: "МояКоллекция-K8s"
        - name: APP_PORT
          value: "8080"
        - name: DB_PATH
          value: "/tmp/collection.db"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
