apiVersion: v1
kind: Service
metadata:
  name: collection-service
  labels:
    app: collection
spec:
  selector:
    app: collection
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  type: NodePort
